In [1]:
!pip install SQLAlchemy==1.4.49

#Please run this in google colab. Import the stroke_data.sqlite file into the content folder for colab.


In [2]:
import sqlalchemy
import pandas as pd

from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

# Database Setup
engine = create_engine("sqlite:////content/stroke_data.sqlite")

# reflect an existing database into a new model
Base = automap_base()

# reflect the tables
Base.prepare(autoload_with=engine)

#test view all classes found by automap
Base.classes.keys()

conn = engine.connect()

#populate stroke data table
stroke_df = pd.read_sql('SELECT * FROM stroke_data', conn)

stroke_df.head()

?                  age       avg_glucose_level                  bmi  \
0  0    1.040584334185826       2.723410903530197    1.193238162209789   
1  1    1.614270327485722  -0.0005227665986433442   0.5893896105370293   
2  2  0.24624988192443203      1.4485291841720218   0.8692218661902591   
3  3   1.5701406356934222      1.5126504540805694  -0.6624915331747888   
4  4   1.6584000192780215      1.7808947977464298  0.07390913959686891   

  ever_married_No ever_married_Yes work_type_Govt_job work_type_Private  \
0               0                1                  0                 1   
1               0                1                  0                 1   
2               0                1                  0                 1   
3               0                1                  0                 0   
4               0                1                  0                 1   

  work_type_Self-employed work_type_children Residence_type_Rural  \
0                       0                  0                    0   
1                       0                  0                    1   
2                       0                  0                    0   
3                       1                  0                    1   
4                       0                  0                    0   

  Residence_type_Urban smoking_status_Unknown smoking_status_formerly smoked  \
0                    1                      0                              1   
1                    0                      0                              0   
2                    1                      0                              0   
3                    0                      0                              0   
4                    1                      0                              1   

  smoking_status_never smoked smoking_status_smokes stroke  
0                           0                     0      1  
1                           1                     0      1  
2                           0                     1      1  
3                           1                     0      1  
4                           0                     0      1

In [3]:
len(stroke_df)

4981

In [4]:
stroke_df = stroke_df.drop(['?'], axis = 1)
stroke_df.head()

age       avg_glucose_level                  bmi  \
0    1.040584334185826       2.723410903530197    1.193238162209789   
1    1.614270327485722  -0.0005227665986433442   0.5893896105370293   
2  0.24624988192443203      1.4485291841720218   0.8692218661902591   
3   1.5701406356934222      1.5126504540805694  -0.6624915331747888   
4   1.6584000192780215      1.7808947977464298  0.07390913959686891   

  ever_married_No ever_married_Yes work_type_Govt_job work_type_Private  \
0               0                1                  0                 1   
1               0                1                  0                 1   
2               0                1                  0                 1   
3               0                1                  0                 0   
4               0                1                  0                 1   

  work_type_Self-employed work_type_children Residence_type_Rural  \
0                       0                  0                    0   
1                       0                  0                    1   
2                       0                  0                    0   
3                       1                  0                    1   
4                       0                  0                    0   

  Residence_type_Urban smoking_status_Unknown smoking_status_formerly smoked  \
0                    1                      0                              1   
1                    0                      0                              0   
2                    1                      0                              0   
3                    0                      0                              0   
4                    1                      0                              1   

  smoking_status_never smoked smoking_status_smokes stroke  
0                           0                     0      1  
1                           1                     0      1  
2                           0                     1      1  
3                           1                     0      1  
4                           0                     0      1

In [5]:
stroke_df = stroke_df.apply(pd.to_numeric, errors='coerce')

In [6]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [7]:
y = stroke_df['stroke']
X = stroke_df.drop(columns='stroke')
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [8]:
nn_model_recall_acc = tf.keras.models.Sequential()

# First hidden layer
nn_model_recall_acc.add(tf.keras.layers.Dense(units=8, activation="LeakyReLU", input_dim=15))

# Second hidden layer
nn_model_recall_acc.add(tf.keras.layers.Dense(units=8, activation="relu"))

# Third hidden layer
nn_model_recall_acc.add(tf.keras.layers.Dense(units=8, activation="softplus"))

#Fourth hidden layer
nn_model_recall_acc.add(tf.keras.layers.Dense(units=8, activation="selu"))

#Fith hidden layer
nn_model_recall_acc.add(tf.keras.layers.Dense(units=8, activation="relu"))

# Output layer
nn_model_recall_acc.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

nn_model_recall_acc.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', tf.keras.metrics.Recall(), tf.keras.metrics.Precision()])

fit_model = nn_model_recall_acc.fit(X_train, y_train, epochs=50)

Epoch 1/50
117/117 [==============================] - 4s 5ms/step - loss: 0.1974 - accuracy: 0.9518 - recall: 0.0000e+00 - precision: 0.0000e+00
Epoch 2/50
117/117 [==============================] - 1s 6ms/step - loss: 0.1743 - accuracy: 0.9518 - recall: 0.0000e+00 - precision: 0.0000e+00
Epoch 3/50
117/117 [==============================] - 1s 10ms/step - loss: 0.1647 - accuracy: 0.9518 - recall: 0.0000e+00 - precision: 0.0000e+00
Epoch 4/50
117/117 [==============================] - 1s 10ms/step - loss: 0.1611 - accuracy: 0.9518 - recall: 0.0000e+00 - precision: 0.0000e+00
Epoch 5/50
117/117 [==============================] - 1s 7ms/step - loss: 0.1592 - accuracy: 0.9518 - recall: 0.0000e+00 - precision: 0.0000e+00
Epoch 6/50
117/117 [==============================] - 1s 4ms/step - loss: 0.1580 - accuracy: 0.9518 - recall: 0.0000e+00 - precision: 0.0000e+00
Epoch 7/50
117/117 [==============================] - 1s 5ms/step - loss: 0.1568 - accuracy: 0.9518 - recall: 0.0000e+00 - preci

In [9]:
y_prediction = nn_model_recall_acc.predict(X_test)

#Create confusion matrix and normalizes it over predicted (columns)
from sklearn.metrics import confusion_matrix
result = confusion_matrix(y_test, y_prediction>.075)
print(result)

39/39 [==============================] - 0s 2ms/step
[[973 205]
 [ 20  48]]


In [10]:
y_prediction = nn_model_recall_acc.predict(X_test)
result = confusion_matrix(y_test, y_prediction>.075, normalize='pred')
print(result)

39/39 [==============================] - 0s 2ms/step
[[0.97985901 0.81027668]
 [0.02014099 0.18972332]]


In [11]:
y_prediction_train = nn_model_recall_acc.predict(X_train)
result = confusion_matrix(y_train, y_prediction_train>.075, normalize='pred')
print(result)

117/117 [==============================] - 0s 2ms/step
[[0.98423037 0.83618582]
 [0.01576963 0.16381418]]


In [12]:
nn_model_recall_acc.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 128       
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 8)                 72        
                                                                 
 dense_3 (Dense)             (None, 8)                 72        
                                                                 
 dense_4 (Dense)             (None, 8)                 72        
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 425
Trainable params: 425
Non-trainable pa

In [13]:
!pip install keras-tuner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 3.1 MB/s eta 0:00:00


In [17]:
def create_model(hp):
    nn_model_optimized = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu', 'LeakyReLU', 'sigmoid', 'softplus', 'selu'])

    # Allow kerastuner to decide number of neurons in first layer
    nn_model_optimized.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=15))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model_optimized.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))

    nn_model_optimized.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model_optimized.compile(loss="binary_crossentropy", optimizer='adam', metrics=['accuracy', tf.keras.metrics.Recall(), tf.keras.metrics.Precision()])

    return nn_model_optimized

In [18]:
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=100,
    hyperband_iterations=5)

# ***WARNING:*** the following code will begin the optimization process. This can take several hours.

If you would like to test the optimized model, please download and use 'Stroke_Predictor.h5'.

In [19]:
tuner.search(X_train,y_train,epochs=50,validation_data=(X_test,y_test))

Trial 1262 Complete [00h 00m 53s]
val_accuracy: 0.9454253315925598

Best val_accuracy So Far: 0.9486356377601624
Total elapsed time: 03h 04m 14s


In [20]:
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'selu',
 'first_units': 7,
 'num_layers': 6,
 'units_0': 9,
 'units_1': 9,
 'units_2': 1,
 'units_3': 1,
 'units_4': 7,
 'units_5': 3,
 'tuner/epochs': 34,
 'tuner/initial_epoch': 12,
 'tuner/bracket': 2,
 'tuner/round': 1,
 'tuner/trial_id': '0463'}

In [23]:
best_model = tuner.get_best_models(1)[0]


In [82]:
y_prediction = best_model.predict(X_test)

#Create confusion matrix and normalizes it over predicted (columns)

result = confusion_matrix(y_test, y_prediction>.0825)
print(result)

39/39 [==============================] - 0s 2ms/step
[[856 322]
 [  9  59]]


# Summary of Results

This optimized model takes around the highest risk third of our testing population and suggests they seek further medical testing for concerns of an oncoming stroke.

At a .0825 threshold, the model catches ~87% of strokes. A total of 381 will be sent for additional testing, and ~15% of those sent will go on to have a stroke, compared to ~5% for the total testing population.

The 9 who have a stroke but are not sent for testing would need the threshold dropped significantly to be caught. This indicates that they are maybe showing signs of an oncoming stroke in a way that is not represented in our data, or showing no signs at all. Additional data could improve the functionality of this and future models.

In [68]:
# Save the model
best_model.save("Stroke_Predictor.h5")

In [70]:
# Load the model
from tensorflow.keras.models import load_model
model = load_model("Stroke_Predictor.h5")

In [71]:
y_prediction = model.predict(X_test)

#Create confusion matrix and normalizes it over predicted (columns)

result = confusion_matrix(y_test, y_prediction>.0825)
print(result)

39/39 [==============================] - 1s 7ms/step
[[856 322]
 [  9  59]]
